[DOGEC]
Title=DogeCash
Address=
Ip=127.0.0.1
Port=51576
Username=
Password=
AddressPrefix=30
ScriptPrefix=19
SecretPrefix=122
COIN=100000000
MinimumAmount=0
TxVersion=1
DustAmount=0
CreateTxMethod=BTC
GetNewKeySupported=true
ImportWithNoScanSupported=true
MinTxFee=6780
BlockTime=60
FeePerByte=15
Confirmations=0
