[LYNX]
Title=Lynx
Address=
Ip=127.0.0.1
Port=8432
Username=
Password=
AddressPrefix=45
ScriptPrefix=22
SecretPrefix=173
COIN=100000000
MinimumAmount=0
TxVersion=1
DustAmount=0
CreateTxMethod=BTC
GetNewKeySupported=true
ImportWithNoScanSupported=true
MinTxFee=678
BlockTime=300
FeePerByte=2
Confirmations=0
