[XVG]
Title=Verge
Address=
Ip=127.0.0.1
Port=20102
Username=
Password=
AddressPrefix=30
ScriptPrefix=33
SecretPrefix=158
COIN=1000000
MinimumAmount=0
TxVersion=1
DustAmount=0
CreateTxMethod=BTC
GetNewKeySupported=false
ImportWithNoScanSupported=false
MinTxFee=67800
BlockTime=30
FeePerByte=150
Confirmations=0
TxWithTimeField=true
